<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="AddRewardProviders.aspx.cs" Inherits="AddRewardProviders" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    
    <link href="Style/desktop.css" rel="stylesheet" />
    <script src="Scripts/Sidebar.js"></script>
    <div id ="sidebar">
        <div class="toggle-btn" onclick="toggleSidebar();">
            <span></span>
            <span></span>
            <span></span>
        </div>
        <ul>
            <li> <asp:Label ID="lblUser" runat="server" Text=""></asp:Label></li>
            <li><a href="AdminPage.aspx">Home</a></li>
            <li> <a href ="/UserOptions.aspx">User Options</a></li>
            <li> <a href="/ViewRewards.aspx">View Rewards</a></li>
            <li> <a href ="/AddRewardProviders.aspx">View Reward Providers</a></li>
            <li>Add Community Events</li>
            <li><a href="/LoginPage.aspx">Logout</a></li>
        </ul>
    </div>
    <asp:Image id = "headerIMG" runat ="server" ImageUrl ="~/Images/Header.png" width ="100%"/>
    <h1>Elk Logistics Rewards System</h1>

    <table style="width: 100%">
        <tr>
            <td style="width: 241px">
                &nbsp;</td>
            <td>
            &nbsp;</td>
        </tr>
    </table>
    <br />
    <div id="RewardProviderGrid">
        <table>
            <tr>
                <td>
                     <asp:GridView ID="grdProviders" ValidationGroup="validNewProvider" AutoGenerateColumns="False" runat="server" style="left: 311px; top: 799px" Width="545px" 
                         OnRowCancelingEdit="grdProviders_RowCancelingEdit" OnRowEditing="grdProviders_RowEditing" OnRowUpdating="grdProviders_RowUpdating" DataKeyNames="ProviderID" ShowHeaderWhenEmpty="True" OnRowDeleting="grdProviders_RowDeleting" AutoGenerateDeleteButton="True">
                        <Columns>                            
                            <asp:CommandField ShowEditButton="true" CausesValidation="true" ValidationGroup="validNewProvider"/>
                            <asp:TemplateField HeaderText="Provider ID">
                                <ItemTemplate>
                                    <asp:Label ID="lblgvProviderID" runat="server" Text='<%# Eval("ProviderID") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Provider Name">
                                <EditItemTemplate>
                                    <asp:TextBox ID="txtgvProviderName" runat="server" Text='<%# Eval("ProviderName") %>'></asp:TextBox>
                                    <asp:RequiredFieldValidator ID="reqgvProviderName" ControlToValidate="txtgvProviderName" Text="(Required)" Display="Dynamic" Runat="server" Font-Bold="True" ForeColor="Red" ValidationGroup="validNewProvider"></asp:RequiredFieldValidator>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="lblgvProviderName" runat="server" Text='<%# Eval("ProviderName") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Provider Email">
                                <EditItemTemplate>
                                    <asp:TextBox ID="txtgvProviderEmail" runat="server" Text='<%# Eval("ProviderEmail") %>' TextMode="SingleLine"></asp:TextBox>
                                    <asp:RequiredFieldValidator ID="reqgvProviderEmail" ControlToValidate="txtgvProviderEmail" Text="(Required)" Display="Dynamic" Runat="server" Font-Bold="True" ForeColor="Red" ValidationGroup="validNewProvider"></asp:RequiredFieldValidator>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="lblgvProviderEmail" runat="server" Text='<%# Eval("ProviderEmail") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                        </Columns>
                        <EmptyDataTemplate>
                            <asp:Label ID="lvlgvNoProvider" runat="server" Text="No Records Found"></asp:Label>
                        </EmptyDataTemplate>
                        </asp:GridView>
                </td>
                <td>
                    <asp:Label ID="lblSearch" runat="server" Text="Search for a provider: "></asp:Label>
                </td>
                <td>
                    <asp:TextBox ID="txtSearch" runat="server"></asp:TextBox>
                </td>
                <td>
                    <asp:Button ID="btnSearch" runat="server" Text="Search" OnClick="btnSearch_Click" CausesValidation="False" />
                </td>
                
            </tr>
        </table>
       
        <br />
        <div id="tblNewProvider">
            <table  style="width: 100%">
                <tr>
                    <td style="width: 115px">
                        <asp:Button ID="btnAddProvider" runat="server" OnClick="btnAddProvider_Click1" Text="Add Reward Provider" CausesValidation="False" />
                    </td>
                    <td>
                        <asp:Button ID="btnClear" runat="server" Text="Clear" CausesValidation="False" OnClick="btnClear_Click1" />
                    &nbsp;&nbsp;
                        <asp:Button ID="AutoFillRewardProviderID" runat="server" OnClick="AutoFillRewardProviderID_Click" Text="AutoFillRewardProvider" Width="167px" />
                    </td>
                </tr>
                <tr>
                    <td width: "10px">
                        <asp:Label ID="lblProviderName" runat="server" Text="Provider Name: " Visible="False"></asp:Label>
                    </td>
                    <td style="width: 80px">
                        <asp:TextBox ID="txtNewProviderName" runat="server" style="margin-left: 0px" Visible="False"></asp:TextBox>
                        <asp:RequiredFieldValidator ID="reqProviderName" ControlToValidate="txtNewProviderName" Text="(Required)" runat="server" ForeColor="Red" style="font-weight: 700"></asp:RequiredFieldValidator>
                    </td>
                </tr>
                <tr>
                    <td style="width: 115px">
                        <asp:Label ID="lblProviderEmail" runat="server" Text="Provider Email: " Visible="False"></asp:Label>
                    </td>
                    <td style="width: 20px">
                        <asp:TextBox ID="txtNewProviderEmail" runat="server" Visible="False" TextMode="Email"></asp:TextBox>
                        <asp:RequiredFieldValidator ID="reqProviderEmail" ControlToValidate="txtNewProviderEmail" Text="(Required)" runat="server" ForeColor="Red" style="font-weight: 700"></asp:RequiredFieldValidator>
                    </td>
                    <td style="width: 145px">
                        <asp:Button ID="btnAdd" runat="server" OnClick="btnAdd_Click1" Text="Add" Visible="False" />
                    </td>
                </tr>
            </table>
    </div>
    </div>
    <asp:Label ID="lblResult" runat="server"></asp:Label>

    
</asp:Content>

