<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="AddRewardProviders.aspx.cs" Inherits="AddRewardProviders" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    
    <table style="width: 100%">
        <tr>
            <td>
                <asp:Label ID="lblSearch" runat="server" Text="Search for a Reward Provider:"></asp:Label>
            </td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td>
                <asp:TextBox ID="txtSearch" runat="server"></asp:TextBox>
            </td>
            <td>
                <asp:Button ID="Button1" runat="server" Text="Search" />
            </td>
        </tr>
    </table>
    <br />
    <div>
        <asp:GridView ID="grdProviders" AutoGenerateColumns="False" runat="server"   
                            AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="ProviderID" ShowHeaderWhenEmpty="True" OnRowEditing="grdProviders_RowEditing" OnRowCancelingEdit="grdProviders_RowCancelingEdit" OnRowUpdating="grdProviders_RowUpdating">
                        <Columns>
                            <asp:TemplateField HeaderText="Provider ID">
                                <FooterTemplate>
                                    <asp:TextBox ID="txtProviderID" runat="server" ReadOnly="True" Text='<%# Eval("ProviderID") %>'></asp:TextBox>
                                </FooterTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="lblProviderID" runat="server" Text='<%# Eval("ProviderID") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Provider Name">
                                <EditItemTemplate>
                                    <asp:TextBox ID="txtProviderName" runat="server" Text='<%# Eval("ProviderName") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <FooterTemplate>
                                    <asp:TextBox ID="txtProviderID" runat="server" ReadOnly="True" Text='<%# Eval("ProviderID") %>'></asp:TextBox>
                                </FooterTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="lblProviderName" runat="server" Text='<%# Eval("ProviderName") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Provider Email">
                                <EditItemTemplate>
                                    <asp:TextBox ID="txtProviderEmail" runat="server" Text='<%# Eval("ProviderEmail") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <FooterTemplate>
                                    <asp:TextBox ID="txtProviderID" runat="server" ReadOnly="True" Text='<%# Eval("ProviderID") %>'></asp:TextBox>
                                </FooterTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="lblProviderEmail" runat="server" Text='<%# Eval("ProviderEmail") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                        </Columns>
                        <EmptyDataTemplate>
                            <asp:Label ID="Label6" runat="server" Text="No Records Found"></asp:Label>
                        </EmptyDataTemplate>
                        </asp:GridView>
    </div>

    <asp:Label ID="lblResult" runat="server"></asp:Label>
    
</asp:Content>

