<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="ManageCommunityPost.aspx.cs" Inherits="ManageCommunityPost" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    
    <link href="Style/desktop.css" rel="stylesheet" />
    <script src="Scripts/Sidebar.js"></script>
    <div id ="sidebar">
        <div class="toggle-btn" onclick="toggleSidebar();">
            <span></span>
            <span></span>
            <span></span>
        </div>
        <ul>
            <li> <asp:Label ID="lblUser" runat="server" Text=""></asp:Label></li>
            <li><a href="AdminPage.aspx">Home</a></li>
            <li> <a href ="/UserOptions.aspx">User Options</a></li>
            <li> <a href="/ViewRewards.aspx">View Rewards</a></li>
            <li> <a href ="/AddRewardProviders.aspx">View Reward Providers</a></li>
            <li>Add Community Events</li>
            <li><a href="/LoginPage.aspx">Logout</a></li>
        </ul>
    </div>
    <div>
    <asp:Image id = "headerIMG" runat ="server" ImageUrl ="~/Images/Header.png" width ="100%"/>
    <h1>Elk Logistics Rewards System</h1>
        <table style="width: 100%">
            <tr>
                <td style="width: 151px">Event Title</td>
                <td style="width: 457px">
                    <asp:TextBox ID="txtFName" runat="server" MaxLength="30"></asp:TextBox>
                    <asp:RequiredFieldValidator ID="reqFName" ControlToValidate="txtFName" Display="Dynamic" Text="(Required)" Font-Bold="true" ForeColor="Red" runat="server"></asp:RequiredFieldValidator>
                </td>
            </tr>
            <tr>
                <td style="width: 151px">Event Description</td>
                <td style="width: 457px">
                    <asp:TextBox ID="txtLName" runat="server" MaxLength="30" Height="99px" TextMode="MultiLine" Width="419px"></asp:TextBox>
                    <asp:RequiredFieldValidator ID="reqLName" ControlToValidate="txtLName" Display="Dynamic" Text="(Required)" Font-Bold="true" ForeColor="Red" runat="server"></asp:RequiredFieldValidator>
                </td>
            </tr>
                        
            </table>
            <div>

                <asp:Button ID="btnInsertEvent" runat="server" OnClick="btnInsertUser_Click" Text="Insert Event" />

            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <asp:Button ID="btnAutoFillEvent" runat="server" OnClick="btnAutoFillUser_Click" Text="AutoFill Event" CausesValidation="False" />

            </div>
        <div>
            <asp:Label ID="lblError" runat="server" Text="No Error"></asp:Label>
        </div>

    </div>
    <br />
    <br />
    <asp:GridView ID="grdUsers" ValidationGroup="validNewEmp" runat="server" AutoGenerateColumns="False" DataKeyNames="EventPostID" OnRowCancelingEdit="grdUsers_RowCancelingEdit" OnRowDeleting="grdUsers_RowDeleting" OnRowEditing="grdUsers_RowEditing" OnRowUpdating="grdUsers_RowUpdating" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
        <Columns>
             <asp:TemplateField HeaderText="EventID">
                <EditItemTemplate>
                    <asp:Label ID="txtgvFName" runat="server" MaxLength="30" Text='<%# Eval("EventPostID") %>' Height="22px" Width="136px" ReadOnly="True"></asp:Label>
                    <%--<asp:RequiredFieldValidator ID="reqgvFName" ControlToValidate="txtgvFName" Text="(Required)" Display="Dynamic" Runat="server" Font-Bold="True" ForeColor="Red" ValidationGroup="validNewEmp"></asp:RequiredFieldValidator>
              --%>  </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="lblFName" runat="server" Text='<%# Eval("EventPostID") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Event Title">
                <EditItemTemplate>
                    <asp:TextBox ID="EventTitleEdit" runat="server" MaxLength="30" Text='<%# Eval("EventTitle") %>' Height="22px" Width="122px"></asp:TextBox>
                    <%--<asp:RequiredFieldValidator ID="reqgvFName" ControlToValidate="txtgvFName" Text="(Required)" Display="Dynamic" Runat="server" Font-Bold="True" ForeColor="Red" ValidationGroup="validNewEmp"></asp:RequiredFieldValidator>
              --%>  </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="lblFName" runat="server" Text='<%# Eval("EventTitle") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Event Description">
                <EditItemTemplate>
                    <asp:TextBox ID="EventDescEdit" runat="server" MaxLength="30" Text='<%# Eval("EventDesc") %>' Height="113px" TextMode="MultiLine" Width="400px"></asp:TextBox>
                   <%-- <asp:RequiredFieldValidator ID="reqgvLName" ControlToValidate="txtgvLName" Text="(Required)" Display="Dynamic" Runat="server" Font-Bold="True" ForeColor="Red" ValidationGroup="validNewEmp"></asp:RequiredFieldValidator>
             --%>   </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="lblLName" runat="server" Text='<%# Eval("EventDesc") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Date Posted">
        
                <EditItemTemplate>
                    <asp:Label ID="DatePostedtxt" runat="server" Text='<%# Eval("DatePosted") %>' ReadOnly="True"></asp:Label>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="DatePostedlbl" runat="server" Text='<%# Eval("DatePosted") %>' ></asp:Label>
                </ItemTemplate>
        
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Admin">
        
                <EditItemTemplate>
                    <asp:Label ID="AdminIDtxt" runat="server" Text='<%# Eval("AdminID") %>' ReadOnly="True"></asp:Label>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="AdminIDtxt" runat="server" Text='<%# Eval("AdminID") %>'></asp:Label>
                </ItemTemplate>
        
            </asp:TemplateField>
        </Columns>
        <EmptyDataTemplate>
            <asp:Label ID="lblEmptly" runat="server" Text="No Records Available"></asp:Label>
        </EmptyDataTemplate>
    </asp:GridView>
</asp:Content>

