<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="AddRewardProviders.aspx.cs" Inherits="AddRewardProviders" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">

    <link href="Style/desktop.css" rel="stylesheet" />
    <script src="Scripts/Sidebar.js"></script>
    <div id ="sidebar">
        <div class="toggle-btn" onclick="toggleSidebar();">
            <span></span>
            <span></span>
            <span></span>
        </div>
        <ul>
            <li>User Options</li>
            <li>View Rewards</li>
            <li> <a href ="/ViewRewardProviders">View Reward Providers</a></li>
            <li>Add Community Events</li>
        </ul>
    </div>


    
    <br />
    <div id="RewardProviderGrid">
        <table>
            <tr>
                <td>
                     <asp:GridView ID="grdProviders" AutoGenerateColumns="False" runat="server"  style="left: 311px; top: 799px" Width="545px" 
                         OnRowCancelingEdit="grdProviders_RowCancelingEdit" OnRowEditing="grdProviders_RowEditing" OnRowUpdating="grdProviders_RowUpdating" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="ProviderID" ShowHeaderWhenEmpty="True" OnRowDeleting="grdProviders_RowDeleting">
                        <Columns>
                            <asp:TemplateField HeaderText="ProviderID">
                                <EditItemTemplate>
                                    <asp:TextBox ID="txtProviderID" runat="server" Text='<%# Eval("ProviderID") %>' ReadOnly="True"></asp:TextBox>
                                </EditItemTemplate>
                                <FooterTemplate>
                                    <asp:TextBox ID="txtProviderID" runat="server" ReadOnly="True" Text='<%# Eval("ProviderID") %>'></asp:TextBox>
                                </FooterTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="lblProviderID" runat="server" Text='<%# Eval("ProviderID") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="ProviderName">
                                <EditItemTemplate>
                                    <asp:TextBox ID="txtProviderName" runat="server" Text='<%# Eval("ProviderName") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <FooterTemplate>
                                    <asp:TextBox ID="txtProviderID" runat="server" ReadOnly="True" Text='<%# Eval("ProviderID") %>'></asp:TextBox>
                                </FooterTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="lblProviderName" runat="server" Text='<%# Eval("ProviderName") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="ProviderEmail">
                                <EditItemTemplate>
                                    <asp:TextBox ID="txtProviderEmail" runat="server" Text='<%# Eval("ProviderEmail") %>' TextMode="MultiLine"></asp:TextBox>
                                </EditItemTemplate>
                                <FooterTemplate>
                                    <asp:TextBox ID="txtProviderID" runat="server" ReadOnly="True" Text='<%# Eval("ProviderID") %>'></asp:TextBox>
                                </FooterTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="lblProviderEmail" runat="server" Text='<%# Eval("ProviderEmail") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                        </Columns>
                        <EmptyDataTemplate>
                            <asp:Label ID="Label6" runat="server" Text="No Records Found"></asp:Label>
                        </EmptyDataTemplate>
                        </asp:GridView>
                </td>
                
            </tr>
        </table>
       
        <br />
        <div id="tblNewProvider">
            <table  style="width: 100%">
                <tr>
                    <td style="width: 115px">
                        <asp:Button ID="btnAddProvider" runat="server" OnClick="btnAddProvider_Click1" Text="Add Reward Provider" />
                    </td>
                    <td>
                        <asp:Button ID="btnClear" runat="server" Text="Clear" OnClick="btnClear_Click" />
                    </td>
                </tr>
                <tr>
                    <td width: "10px">
                        <asp:Label ID="lblProviderName" runat="server" Text="Provider Name: " Visible="False"></asp:Label>
                    </td>
                    <td style="width: 80px">
                        <asp:TextBox ID="txtNewProviderName" runat="server" style="margin-left: 0px" Visible="False"></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <td style="width: 115px">
                        <asp:Label ID="lblProviderEmail" runat="server" Text="Provider Email: " Visible="False"></asp:Label>
                    </td>
                    <td style="width: 20px">
                        <asp:TextBox ID="txtNewProviderEmail" runat="server" Visible="False"></asp:TextBox>
                    </td>
                    <td style="width: 145px">
                        <asp:Button ID="btnAdd" runat="server" OnClick="btnAdd_Click" Text="Add" Visible="False" />
                    </td>
                </tr>
            </table>
    </div>
    </div>
    <br />
    <asp:Label ID="lblResult" runat="server"></asp:Label>

    
</asp:Content>

